language: node_js
node_js:
  - 12
  - 6
  - 5
  - 4
before_install:
  - git fetch --unshallow
  - npm config set depth 0
  - npm install --global npm@3
script:
  - /bin/bash ./.scripts/lint-commits.sh
  - NODE_ENV=production npm run build
  - rm -fr ./dist
  - npm run lint
  - flow
  - nyc --silent npm run test
  - nyc report --reporter=text-lcov | coveralls
  - nyc check-coverage --lines 90
after_success:
  - travis-after-all && ./.scripts/release.sh
notifications:
  email: false
sudo: false
